"""Auto-generated GPU binding constants.

DO NOT EDIT THIS FILE MANUALLY.
Run tools/generate_bindings.py to regenerate from gpu/binding_definitions.py.
"""

from __future__ import annotations

# ── SSBO Bindings ──────────────────────────────────────────────────────────────

SSBO_CELLS_READ = 0
SSBO_CELLS_WRITE = 1
SSBO_RULES = 2
SSBO_RESERVATIONS = 8
SSBO_COUNTERS = 9

# ── Image Bindings ───────────────────────────────────────────────────────────────

IMAGE_VELOCITY_IN = 3
IMAGE_VELOCITY_OUT = 4
IMAGE_DIVERGENCE = 4
IMAGE_PRESSURE_IN = 5
IMAGE_PRESSURE_OUT = 6
IMAGE_DISPLAY = 7
IMAGE_VORTICITY = 8
IMAGE_TEMPERATURE_IN = 11
IMAGE_TEMPERATURE_OUT = 12
IMAGE_CHARGE_IN = 9
IMAGE_CHARGE_OUT = 10
IMAGE_NUTRIENT_IN = 13
IMAGE_NUTRIENT_OUT = 14
IMAGE_MOISTURE_IN = 15
IMAGE_MOISTURE_OUT = 16
IMAGE_HUMIDITY_IN = 17
IMAGE_HUMIDITY_OUT = 18
IMAGE_BLOOM_A = 19
IMAGE_BLOOM_B = 20

# ── UBO Bindings ────────────────────────────────────────────────────────────────

UBO_SIM_CONFIG = 3
UBO_EXPLOSION = 4
UBO_EXPLOSION_VFX = 5
UBO_WIND = 6