// Auto-generated GPU binding definitions.
//
// DO NOT EDIT THIS FILE MANUALLY.
// Run tools/generate_bindings.py to regenerate from gpu/binding_definitions.py.

// ── SSBO Bindings (Shader Storage Buffer Objects) ──────────────────────────────

layout(std430, binding = 0) readonly buffer Cells_read { uint cells_read[]; };
layout(std430, binding = 1) writeonly buffer Cells_write { uint cells_write[]; };
layout(std430, binding = 2) readonly buffer Rules { float rules[]; };
layout(std430, binding = 8) coherent buffer Reservations { uint reservations[]; };
layout(std430, binding = 9) coherent buffer Counters { uint counters[]; };

// ── Image2D Texture Bindings ────────────────────────────────────────────────────

layout(binding = 3, rg32f) read uniform image2D velocity_in;
layout(binding = 4, rg32f) write uniform image2D velocity_out;
layout(binding = 4, r32f) write uniform image2D divergence;
layout(binding = 5, r32f) read uniform image2D pressure_in;
layout(binding = 6, r32f) write uniform image2D pressure_out;
layout(binding = 7, rgba8) write uniform image2D display;
layout(binding = 8, r32f) readwrite uniform image2D vorticity;
layout(binding = 11, r32f) read uniform image2D temperature_in;
layout(binding = 12, r32f) write uniform image2D temperature_out;
layout(binding = 9, r32f) read uniform image2D charge_in;
layout(binding = 10, r32f) write uniform image2D charge_out;
layout(binding = 13, r32f) read uniform image2D nutrient_in;
layout(binding = 14, r32f) write uniform image2D nutrient_out;
layout(binding = 15, r32f) read uniform image2D moisture_in;
layout(binding = 16, r32f) write uniform image2D moisture_out;
layout(binding = 17, r32f) read uniform image2D humidity_in;
layout(binding = 18, r32f) write uniform image2D humidity_out;
layout(binding = 19, rgba8) readwrite uniform image2D bloom_a;
layout(binding = 20, rgba8) readwrite uniform image2D bloom_b;

// ── UBO Bindings (Uniform Buffer Objects) ─────────────────────────────────────────

layout(std140, binding = 3) uniform SimConfig { /* struct defined in uniforms.glsl */ };
layout(std140, binding = 4) uniform ExplosionConfig { /* struct defined in uniforms.glsl */ };
layout(std140, binding = 5) uniform ExplosionVfxConfig { /* struct defined in uniforms.glsl */ };
layout(std140, binding = 6) uniform WindConfig { /* struct defined in uniforms.glsl */ };