"""Auto-generate GPU binding constants and GLSL includes from single source of truth.

Run this script after modifying gpu/binding_definitions.py to regenerate:
- core/generated_constants.py (Python constants)
- shaders/generated_bindings.glsl (GLSL include file)
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

# Import binding_definitions directly without triggering gpu package imports
binding_definitions_path = Path(__file__).parent.parent / "gpu" / "binding_definitions.py"
spec = importlib.util.spec_from_file_location("binding_definitions", str(binding_definitions_path))
binding_definitions = importlib.util.module_from_spec(spec)
sys.modules["binding_definitions"] = binding_definitions
spec.loader.exec_module(binding_definitions)

ALL_BINDINGS = binding_definitions.ALL_BINDINGS
BindingKind = binding_definitions.BindingKind


def generate_python_constants(output_path: Path) -> None:
    """Generate Python constants file with all binding indices."""
    lines: list[str] = []
    lines.append('"""Auto-generated GPU binding constants.')
    lines.append("")
    lines.append("DO NOT EDIT THIS FILE MANUALLY.")
    lines.append("Run tools/generate_bindings.py to regenerate from gpu/binding_definitions.py.")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("# ── SSBO Bindings ──────────────────────────────────────────────────────────────")
    lines.append("")

    for b in ALL_BINDINGS:
        if b.kind == BindingKind.SSBO:
            const_name = f"SSBO_{b.name.upper()}"
            lines.append(f"{const_name} = {b.binding}")

    lines.append("")
    lines.append("# ── Image Bindings ───────────────────────────────────────────────────────────────")
    lines.append("")

    for b in ALL_BINDINGS:
        if b.kind == BindingKind.IMAGE:
            const_name = f"IMAGE_{b.name.upper()}"
            lines.append(f"{const_name} = {b.binding}")

    lines.append("")
    lines.append("# ── UBO Bindings ────────────────────────────────────────────────────────────────")
    lines.append("")

    # Map binding names to expected constant names for backward compatibility
    ubo_name_map = {
        "SimConfig": "UBO_SIM_CONFIG",
        "ExplosionConfig": "UBO_EXPLOSION",
        "ExplosionVfxConfig": "UBO_EXPLOSION_VFX",
        "WindConfig": "UBO_WIND",
    }

    for b in ALL_BINDINGS:
        if b.kind == BindingKind.UBO:
            const_name = ubo_name_map.get(b.name, f"UBO_{b.name.upper()}")
            lines.append(f"{const_name} = {b.binding}")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated: {output_path}")


def generate_glsl_bindings(output_path: Path) -> None:
    """Generate GLSL include file with all binding declarations."""
    lines: list[str] = []
    lines.append("// Auto-generated GPU binding definitions.")
    lines.append("//")
    lines.append("// DO NOT EDIT THIS FILE MANUALLY.")
    lines.append("// Run tools/generate_bindings.py to regenerate from gpu/binding_definitions.py.")
    lines.append("")
    lines.append("// ── SSBO Bindings (Shader Storage Buffer Objects) ──────────────────────────────")
    lines.append("")

    for b in ALL_BINDINGS:
        if b.kind == BindingKind.SSBO:
            # Remove trailing [] from glsl_type to get base type, then add single [] for unsized array
            base_type = b.glsl_type.rstrip('[]')
            # Use capitalized name for block name to avoid conflict with member name
            block_name = b.name[0].upper() + b.name[1:] if b.name else b.name
            lines.append(f"layout(std430, binding = {b.binding}) {b.access} buffer {block_name} {{ {base_type} {b.name}[]; }};")

    lines.append("")
    lines.append("// ── Image2D Texture Bindings ────────────────────────────────────────────────────")
    lines.append("")

    for b in ALL_BINDINGS:
        if b.kind == BindingKind.IMAGE:
            lines.append(f"layout(binding = {b.binding}, {b.glsl_type}) {b.access} uniform image2D {b.name};")

    lines.append("")
    lines.append("// ── UBO Bindings (Uniform Buffer Objects) ─────────────────────────────────────────")
    lines.append("")

    for b in ALL_BINDINGS:
        if b.kind == BindingKind.UBO:
            # UBOs have structured layouts, we just declare the binding here
            # The actual struct definition is in uniforms.glsl
            lines.append(f"layout(std140, binding = {b.binding}) uniform {b.name} {{ /* struct defined in uniforms.glsl */ }};")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated: {output_path}")


def main() -> None:
    """Main entry point."""
    project_root = Path(__file__).parent.parent
    constants_path = project_root / "core" / "generated_constants.py"
    glsl_path = project_root / "shaders" / "generated_bindings.glsl"

    print("Generating GPU bindings from gpu/binding_definitions.py...")
    generate_python_constants(constants_path)
    generate_glsl_bindings(glsl_path)
    print("Done!")


if __name__ == "__main__":
    main()
